version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/chatapp
      - SECRET_KEY=change_me_in_prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://0.0.0.0:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5173"]
    depends_on:
      - backend

volumes:
  pgdata:
