repos:
  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.2
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8

        args: [ --max-line-length=120, --ignore=E203 & W503 & E221 ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files" ]
      - id: isort
        name: isort (cython)
        args: [ "--profile", "black", "--filter-files" ]
        types: [ cython ]
      - id: isort
        name: isort (pyi)
        args: [ "--profile", "black", "--filter-files" ]
        types: [ pyi ]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "--rcfile=.pylintrc", "--max-line-length=120", "--max-locals=60", "--max-args=8",
                "--disable=C0116,C0114,C0115,E0611,E0401" ]

